# .graphclientrc.yml
sources:
  - name: cryptopunks
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/itsjerryokolo/cryptopunks
  # - name: ens
  #   handler:
  #     graphql:
  #       endpoint: https://api.thegraph.com/subgraphs/name/ensdomains/ens

