# .graphclientrc.yml
sources:
  - name: ens
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/ensdomains/ens
plugins:
  - pollingLive:
      defaultInterval: 500


